<?php

namespace AppBundle\Repository;

/**
 * PostVisiblityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostVisiblityRepository extends \Doctrine\ORM\EntityRepository
{
}
