# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
  listener.requestresponse:
    class: AppBundle\EventListener\EventListener
    arguments: []
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
